menu:
  Blog: /
  Archive: /archives/
  GitHub: https://github.com/iuhoay
  Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-44428878-1

# Copyright Infomation
startyear: 2012
